apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{appName}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{appName}}
  minReplicas: {{minReplicas}}
  maxReplicas: {{maxReplicas}}
  targetCPUUtilizationPercentage: {{cpuUtilPercentage}}